// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtImWsjeZDheALj7U2UfHJmNq4ZcefriI',
    appId: '1:37135938404:web:6af4b53b98afca14a8c071',
    messagingSenderId: '37135938404',
    projectId: 'login-react-193c0',
    authDomain: 'login-react-193c0.firebaseapp.com',
    storageBucket: 'login-react-193c0.firebasestorage.app',
    measurementId: 'G-XGZYKCKYR9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEBGEbNd0H814YXkCwOhZ4L0cvLkbmGNQ',
    appId: '1:37135938404:android:54f85761e99d45dda8c071',
    messagingSenderId: '37135938404',
    projectId: 'login-react-193c0',
    storageBucket: 'login-react-193c0.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtImWsjeZDheALj7U2UfHJmNq4ZcefriI',
    appId: '1:37135938404:web:e83b1d2d0d8d5c66a8c071',
    messagingSenderId: '37135938404',
    projectId: 'login-react-193c0',
    authDomain: 'login-react-193c0.firebaseapp.com',
    storageBucket: 'login-react-193c0.firebasestorage.app',
    measurementId: 'G-FPFMPFLN9L',
  );
}
